### ISSUE TITLE
IMNN when you only have derivatives of the mean

### ISSUE THREAD

**Issue by wcoulton** [tomcharnock/information_maximiser#10]
As we discussed it would be nice to be able to use the code when you have access to derivatives of the mean but not derivatives for each simulation. Currently this can be done by passing n copies of the derivative of the mean, but this is suboptimal (as the derivatives are now potentially biased?). 

I think that the functionality for this should be easy to add. You need to process the mean through the neural network and then combine the network derivative (of the mean) with the derivative of the mean wrt to the parameters. 

Thanks!

**Comment by tomcharnock** [comment]
@wcoulton I had a look at this problem since we left the other day. There is a slight problem in that NN(mean(d)) != mean(NN(d)) since NN is a non-linear function you can't just commute the expectation and the network. I think we can essentially get around this by doing a Taylor expansion on NN(mean(d)) which is cheap with TF2, but I'm not sure how happy I am about doing that. When I'm back in Paris I'll have a proper sit down and think about how to get around this. I'll keep you in the loop.

I think this is a feature which definitely needs adding.

**Comment by bwandelt** [comment]
One only ever needs the derivative of the mean - this was an implementation artifact, not an issue with the approach.

**Comment by tomcharnock** [comment]
One only ever needs the derivative of the mean of the summaries, but this thread about is using the derivative of the mean of the data - which we can't do.
